#!/bin/bash

echo "==================================="
echo "  Data Persistence Features Check"
echo "==================================="
echo ""

echo "✓ Checking HTML changes..."
grep -q "ratings-counter" index.html && echo "  • Ratings counter element added" || echo "  ✗ Missing ratings counter"
grep -q "last-update" index.html && echo "  • Last update element added" || echo "  ✗ Missing last update"
grep -q "import-data-btn" index.html && echo "  • Import button added" || echo "  ✗ Missing import button"
grep -q "import-file-input" index.html && echo "  • Import file input added" || echo "  ✗ Missing file input"
grep -q "actions-grid" index.html && echo "  • Actions grid layout added" || echo "  ✗ Missing actions grid"

echo ""
echo "✓ Checking CSS changes..."
grep -q "data-indicators" styles.css && echo "  • Data indicators styles added" || echo "  ✗ Missing indicator styles"
grep -q "btn-primary" styles.css && echo "  • Primary button styles added" || echo "  ✗ Missing primary button"
grep -q "actions-grid" styles.css && echo "  • Actions grid styles added" || echo "  ✗ Missing grid styles"
grep -q "indicator.unsaved" styles.css && echo "  • Unsaved state styles added" || echo "  ✗ Missing unsaved styles"

echo ""
echo "✓ Checking JavaScript changes..."
grep -q "checkLocalStorageAvailability" uiLayout.js && echo "  • localStorage check function added" || echo "  ✗ Missing localStorage check"
grep -q "handleStorageError" uiLayout.js && echo "  • Storage error handler added" || echo "  ✗ Missing error handler"
grep -q "updateDataIndicators" uiLayout.js && echo "  • Update indicators function added" || echo "  ✗ Missing update function"
grep -q "handleImportClick" uiLayout.js && echo "  • Import click handler added" || echo "  ✗ Missing import handler"
grep -q "handleImportFile" uiLayout.js && echo "  • Import file handler added" || echo "  ✗ Missing file handler"
grep -q "localStorageAvailable" uiLayout.js && echo "  • localStorage availability tracking added" || echo "  ✗ Missing availability tracking"

echo ""
echo "✓ Checking function integration..."
COUNT=$(grep -c "updateDataIndicators()" uiLayout.js)
echo "  • updateDataIndicators() called $COUNT times"

echo ""
echo "==================================="
echo "  All checks completed!"
echo "==================================="
echo ""
echo "To test manually:"
echo "  1. Open index.html in a browser"
echo "  2. Rate some movies"
echo "  3. Reload the page - data should persist"
echo "  4. Click 'Save & Export' to download JSON"
echo "  5. Click 'Clear All Data' to clear ratings"
echo "  6. Click 'Import Ratings' to restore from JSON"
echo ""
echo "For automated tests, open test-persistence.html"
