#!/bin/bash

echo "=========================================="
echo "  Exploration UI Module - Verification"
echo "=========================================="
echo ""

echo "✓ Checking files..."
[ -f explorationUI.js ] && echo "  • explorationUI.js exists" || echo "  ✗ Missing explorationUI.js"
[ -f EXPLORATION_UI.md ] && echo "  • EXPLORATION_UI.md exists" || echo "  ✗ Missing documentation"
[ -f test-exploration.html ] && echo "  • test-exploration.html exists" || echo "  ✗ Missing test page"

echo ""
echo "✓ Checking HTML integration..."
grep -q "exploration-section" index.html && echo "  • Exploration section added to HTML" || echo "  ✗ Missing HTML section"
grep -q "filter-controls" index.html && echo "  • Filter controls container added" || echo "  ✗ Missing filter controls"
grep -q "cluster-display" index.html && echo "  • Cluster display added" || echo "  ✗ Missing cluster display"
grep -q "timeline-container" index.html && echo "  • Timeline container added" || echo "  ✗ Missing timeline"

echo ""
echo "✓ Checking CSS..."
grep -q "filter-controls" styles.css && echo "  • Filter control styles added" || echo "  ✗ Missing filter styles"
grep -q "cluster-card" styles.css && echo "  • Cluster card styles added" || echo "  ✗ Missing cluster styles"
grep -q "timeline-period" styles.css && echo "  • Timeline styles added" || echo "  ✗ Missing timeline styles"
grep -q "filter-notice" styles.css && echo "  • Filter notice style added" || echo "  ✗ Missing notice style"

echo ""
echo "✓ Checking JavaScript integration..."
grep -q "import.*ExplorationUI" uiLayout.js && echo "  • ExplorationUI imported" || echo "  ✗ Missing import"
grep -q "ExplorationUI.init" uiLayout.js && echo "  • ExplorationUI initialized" || echo "  ✗ Missing initialization"
grep -q "ExplorationUI.update" uiLayout.js && echo "  • ExplorationUI.update() called" || echo "  ✗ Missing update calls"
grep -q "handleExplorationFilterChange" uiLayout.js && echo "  • Filter change handler added" || echo "  ✗ Missing filter handler"

echo ""
echo "✓ Checking syntax..."
node -c explorationUI.js 2>/dev/null && echo "  • explorationUI.js syntax valid" || echo "  ✗ Syntax error in explorationUI.js"
node -c uiLayout.js 2>/dev/null && echo "  • uiLayout.js syntax valid" || echo "  ✗ Syntax error in uiLayout.js"

echo ""
echo "✓ Feature checklist:"
echo "  • Filter controls with AND logic"
echo "  • Recommendations filtering"
echo "  • Radar chart dimming (optional)"
echo "  • Taste clusters analysis"
echo "  • Taste journey timeline"
echo "  • Trend analysis"
echo "  • Performance optimized (100+ movies)"

echo ""
echo "=========================================="
echo "  All checks completed!"
echo "=========================================="
echo ""
echo "To test:"
echo "  1. Open index.html in a browser"
echo "  2. Rate 8-10 movies"
echo "  3. Scroll to 'Explore Your Taste' section"
echo "  4. Test each feature"
echo ""
echo "For detailed tests: open test-exploration.html"
